apiVersion: 1

groups:
  - orgId: 1
    name: server
    folder: Infrastructure
    interval: 1m

    rules:
      - uid: server_disk_usage_warning
        title: Disco do servidor acima de 80%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_filesystem_avail_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                      /
                      node_filesystem_size_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                    )
                  )
                ) > bool 80

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: Disco do servidor acima de 80%
          description: |
            O filesystem {{ $labels.mountpoint }} do servidor {{ $labels.server }}
            está com mais de 80% de uso há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: disk

      - uid: server_disk_usage_critical
        title: Disco do servidor acima de 90%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_filesystem_avail_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                      /
                      node_filesystem_size_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                    )
                  )
                ) > bool 90

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 5m

        annotations:
          summary: Disco do servidor acima de 90%
          description: |
            O filesystem {{ $labels.mountpoint }} do servidor {{ $labels.server }}
            está com mais de 90% de uso há mais de 5 minutos.

        labels:
          severity: critical
          service: server
          component: disk

      - uid: server_memory_usage_warning
        title: Memória RAM acima de 80%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_memory_MemAvailable_bytes{
                        server!=""
                      }
                      /
                      node_memory_MemTotal_bytes{
                        server!=""
                      }
                    )
                  )
                ) > bool 80

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: Memória RAM acima de 80%
          description: |
            O servidor {{ $labels.server }}
            está com uso de memória RAM acima de 80%
            há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: memory


      - uid: server_memory_usage_critical
        title: Memória RAM acima de 90%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_memory_MemAvailable_bytes{
                        server!=""
                      }
                      /
                      node_memory_MemTotal_bytes{
                        server!=""
                      }
                    )
                  )
                ) > bool 90

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 5m

        annotations:
          summary: Memória RAM acima de 90%
          description: |
            O servidor {{ $labels.server }}
            está com uso de memória RAM acima de 90%
            há mais de 5 minutos.

        labels:
          severity: critical
          service: server
          component: memory


      - uid: server_oom_killer_detected
        title: OOM Killer detectado no servidor
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                increase(
                  node_vmstat_oom_kill{
                    server!=""
                  }[5m]
                ) > bool 0

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: OK
        execErrState: Alerting

        for: 0m

        annotations:
          summary: OOM Killer detectado
          description: |
            O kernel executou OOM Killer no servidor
            {{ $labels.server }} nos últimos 5 minutos.

        labels:
          severity: critical
          service: server
          component: memory

      - uid: server_cpu_usage_warning
        title: CPU do servidor acima de 80%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                100 - (
                  avg by(server)(
                    rate(node_cpu_seconds_total{
                      mode="idle",
                      server!=""
                    }[5m])
                  ) * 100
                ) > bool 80

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: CPU acima de 80%
          description: |
            O servidor {{ $labels.server }}
            está com uso de CPU acima de 80%
            há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: cpu


      - uid: server_cpu_usage_critical
        title: CPU do servidor acima de 95%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                100 - (
                  avg by(server)(
                    rate(node_cpu_seconds_total{
                      mode="idle",
                      server!=""
                    }[5m])
                  ) * 100
                ) > bool 95

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 5m

        annotations:
          summary: CPU acima de 95%
          description: |
            O servidor {{ $labels.server }}
            está com uso de CPU acima de 95%
            há mais de 5 minutos.

        labels:
          severity: critical
          service: server
          component: cpu


      - uid: server_load_average_warning
        title: Load average alto no servidor
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  node_load5{server!=""}
                  /
                  on(server) group_left
                  count by(server)(
                    count by(server, cpu)(
                      node_cpu_seconds_total{mode="idle", server!=""}
                    )
                  )
                )
                > bool 1.5
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: Load average alto
          description: |
            O servidor {{ $labels.server }}
            está com load average acima de 1.5 por core
            há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: cpu


      - uid: server_load_average_critical
        title: Load average crítico no servidor
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  node_load5{server!=""}
                  /
                  on(server) group_left
                  count by(server)(
                    count by(server, cpu)(
                      node_cpu_seconds_total{mode="idle", server!=""}
                    )
                  )
                )
                > bool 2
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 5m

        annotations:
          summary: Load average crítico
          description: |
            O servidor {{ $labels.server }}
            está com load average acima de 2 por core
            há mais de 5 minutos.

        labels:
          severity: critical
          service: server
          component: cpu


      - uid: server_iowait_warning
        title: IO Wait alto no servidor
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                avg by(server)(
                  rate(node_cpu_seconds_total{
                    mode="iowait",
                    server!=""
                  }[5m])
                ) * 100 > bool 20

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: IO Wait alto
          description: |
            O servidor {{ $labels.server }}
            está com IO Wait acima de 20%
            há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: cpu

      - uid: server_down
        title: Servidor offline
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 120
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                up{
                  job="node-exporter",
                  server!=""
                } == bool 0

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 2m

        annotations:
          summary: Servidor offline
          description: |
            O servidor {{ $labels.server }}
            está offline ou o node exporter
            não responde há mais de 2 minutos.

        labels:
          severity: critical
          service: server
          component: host


      - uid: server_reboot_detected
        title: Reboot detectado no servidor
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 900
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                changes(
                  node_boot_time_seconds{
                    server!=""
                  }[15m]
                ) > bool 0

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: OK
        execErrState: Alerting

        for: 0m

        annotations:
          summary: Reboot detectado
          description: |
            O servidor {{ $labels.server }}
            foi reiniciado nos últimos 15 minutos.

        labels:
          severity: warning
          service: server
          component: host