apiVersion: 1

groups:
  - orgId: 1
    name: server
    folder: Infrastructure
    interval: 1m

    rules:
      - uid: server_disk_usage_warning
        title: Disco do servidor acima de 80%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_filesystem_avail_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                      /
                      node_filesystem_size_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                    )
                  )
                ) > bool 80

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: Disco do servidor acima de 80%
          description: |
            O filesystem {{ $labels.mountpoint }} do servidor {{ $labels.server }}
            está com mais de 80% de uso há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: disk

      - uid: server_disk_usage_critical
        title: Disco do servidor acima de 90%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_filesystem_avail_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                      /
                      node_filesystem_size_bytes{
                        server!="",
                        fstype!~"tmpfs|devtmpfs|overlay|squashfs",
                        mountpoint!~"/run.*|/var/lib/docker/.*"
                      }
                    )
                  )
                ) > bool 90

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 5m

        annotations:
          summary: Disco do servidor acima de 90%
          description: |
            O filesystem {{ $labels.mountpoint }} do servidor {{ $labels.server }}
            está com mais de 90% de uso há mais de 5 minutos.

        labels:
          severity: critical
          service: server
          component: disk

      - uid: server_memory_usage_warning
        title: Memória RAM acima de 80%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_memory_MemAvailable_bytes{
                        server!=""
                      }
                      /
                      node_memory_MemTotal_bytes{
                        server!=""
                      }
                    )
                  )
                ) > bool 80

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 10m

        annotations:
          summary: Memória RAM acima de 80%
          description: |
            O servidor {{ $labels.server }}
            está com uso de memória RAM acima de 80%
            há mais de 10 minutos.

        labels:
          severity: warning
          service: server
          component: memory


      - uid: server_memory_usage_critical
        title: Memória RAM acima de 90%
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                (
                  100 *
                  (
                    1 -
                    (
                      node_memory_MemAvailable_bytes{
                        server!=""
                      }
                      /
                      node_memory_MemTotal_bytes{
                        server!=""
                      }
                    )
                  )
                ) > bool 90

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: Alerting
        execErrState: Alerting

        for: 5m

        annotations:
          summary: Memória RAM acima de 90%
          description: |
            O servidor {{ $labels.server }}
            está com uso de memória RAM acima de 90%
            há mais de 5 minutos.

        labels:
          severity: critical
          service: server
          component: memory


      - uid: server_oom_killer_detected
        title: OOM Killer detectado no servidor
        condition: A

        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0

            datasourceUid: prometheus

            model:
              datasource:
                type: prometheus
                uid: prometheus

              editorMode: code

              expr: |
                increase(
                  node_vmstat_oom_kill{
                    server!=""
                  }[5m]
                ) > bool 0

              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

        noDataState: OK
        execErrState: Alerting

        for: 0m

        annotations:
          summary: OOM Killer detectado
          description: |
            O kernel executou OOM Killer no servidor
            {{ $labels.server }} nos últimos 5 minutos.

        labels:
          severity: critical
          service: server
          component: memory