apiVersion: 1

# Ordem importa: datasources referenciados (loki) devem vir antes (tempo).
datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: $GRAFANA_LOKI_DATASOURCE_URL # default: http://loki:3100
    basicAuth: $GRAFANA_BASIC_AUTH_ENABLED # default: false
    basicAuthUser: $GRAFANA_BASIC_AUTH_USERNAME
    secureJsonData:
      basicAuthPassword: $GRAFANA_BASIC_AUTH_PASSWORD
    isDefault: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: $GRAFANA_PROMETHEUS_DATASOURCE_URL # default: http://prometheus:9090
    basicAuth: $GRAFANA_BASIC_AUTH_ENABLED # default: false
    basicAuthUser: $GRAFANA_BASIC_AUTH_USERNAME
    secureJsonData:
      basicAuthPassword: $GRAFANA_BASIC_AUTH_PASSWORD
    isDefault: false
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: $TEMPO_QUERY_API # default: http://tempo:3200
    basicAuth: $GRAFANA_BASIC_AUTH_ENABLED # default: false
    basicAuthUser: $GRAFANA_BASIC_AUTH_USERNAME
    secureJsonData:
      basicAuthPassword: $GRAFANA_BASIC_AUTH_PASSWORD
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
      lokiSearch:
        datasourceUid: loki
    isDefault: false
    editable: false
