apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: $GRAFANA_LOKI_DATASOURCE_URL # default: http://loki:3100
    basicAuth: $GRAFANA_BASIC_AUTH_ENABLED # default: false
    basicAuthUser: $GRAFANA_BASIC_AUTH_USERNAME
    secureJsonData:
      basicAuthPassword: $GRAFANA_BASIC_AUTH_PASSWORD
    isDefault: true
