services:
  loki:
    image: grafana/loki:2.9.17
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./.data/loki-data:/var/loki
    command: -config.file=/etc/loki/loki-config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki
      - traefik-proxy

