services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel:/etc/otel:ro
    networks:
      - observability