services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel:/etc/otel:ro
    networks:
      - observability
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5